Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# create a pydantic model (or a json-schema) defining the fields of interest
class AutoUiExample(BaseModel):
    text: str = Field(default="Test", description="This description is very important")


import pathlib

value = {"text": "this is a value"}
ui = AutoVjsf(schema=AutoUiExample, value=value, path=pathlib.Path("test.json"))
display(ui)  # uncomment
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 9[0m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mpathlib[39;00m
[1;32m      8[0m value [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mtext[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mthis is a value[39m[38;5;124m"[39m}
[0;32m----> 9[0m ui [38;5;241m=[39m AutoVjsf(schema[38;5;241m=[39mAutoUiExample, value[38;5;241m=[39mvalue, path[38;5;241m=[39mpathlib[38;5;241m.[39mPath([38;5;124m"[39m[38;5;124mtest.json[39m[38;5;124m"[39m))
[1;32m     10[0m display(ui)

File [0;32m~/work/ipyautoui/ipyautoui/src/ipyautoui/autovjsf.py:109[0m, in [0;36mAutoVjsf.__init__[0;34m(self, schema, **kwargs)[0m
[1;32m    105[0m [38;5;28mself[39m[38;5;241m.[39m_value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mautowidget[38;5;241m.[39mvalue
[1;32m    106[0m [38;5;28mself[39m[38;5;241m.[39m_init_controls()
[1;32m    107[0m [38;5;28mself[39m[38;5;241m.[39mchildren [38;5;241m=[39m [
[1;32m    108[0m     [38;5;28mself[39m[38;5;241m.[39msavebuttonbar,
[0;32m--> 109[0m     [38;5;28mself[39m[38;5;241m.[39mhbx_title,
[1;32m    110[0m     [38;5;28mself[39m[38;5;241m.[39mhtml_description,
[1;32m    111[0m     [38;5;28mself[39m[38;5;241m.[39mautowidget,
[1;32m    112[0m     [38;5;28mself[39m[38;5;241m.[39mvbx_showraw,
[1;32m    113[0m ]

[0;31mAttributeError[0m: 'AutoVjsf' object has no attribute 'hbx_title'
AttributeError: 'AutoVjsf' object has no attribute 'hbx_title'

